### ISSUE TITLE
Does not work on iPhones

### ISSUE THREAD

**Issue by simonneutert** [chr15m/scittle-tiny-slides#1]
Hey @chr15m,

I visited your project https://chr15m.github.io/barcamp-whats-the-point-of-lisp/ on the phone, but wasn't able to click through.

Device tested with: iPhone 13

---

So, I decided to tinker a bit with the code ... and if you like, I would love to contribute and open a PR ✌️ 

My conclusion: \
The listeners on the body did not fire, as the body seems to not be targeted properly when clicking/tapping in mobile Safari. I added a possibility to check the event target against: \
`<main>...</main>` - we might have to work on the css a little to make it work in portrait mode... and in landscape mode I would try to stretch `#main` from left to right taking over the full width. That's just my first thought tbh.

The new helper function:

```clojure
(defn main-dom-element [document]
  (first (.getElementsByTagName document "main")))
```

modifying `tap`:

```Clojure
(defn tap
  [ev]
  (when (or (= (aget ev "target") (aget js/document "body"))
            (= (aget ev "target") (main-dom-element js/document))) ;; 👈
    (let [x (aget ev "clientX")
          w (aget js/window "innerWidth")]
      (if (< x (/ w 2))
        (swap! state update :slide dec)
        (swap! state update :slide inc)))))
```

I'd be happy to help 👍

**Comment by chr15m** [comment]
@simonneutert awesome, thanks very much for looking into this.

I found there can be issues with tapping on the body anyway, as sometimes the user might want to click a link, and sometimes a p tag covers the tap area.

I was thinking maybe a better strategy might be to put two large transparent squares in the bottom left of the screen, and then making them apparent by temporarily flashing them when the user touches the screen.

Anyway, I'm happy to merge a PR with your fix and that could be looked at later. Thanks!

**Comment by simonneutert** [comment]
Either flashing or maybe with `css-grid` can help with this 🤔 

I will investigate a little and get back to you! I envision it something like this, when on a touch device:

||||
|---|---|---|
| `<` |`<section></section>`| `>` |
||optional FOOTER||

**Comment by chr15m** [comment]
You could add a new component here: https://github.com/chr15m/scittle-tiny-slides/blob/main/slides.cljs#L69 called e.g. `[component:touch-ui]` and that can render the left right tappable areas on the screen positioned absolutely and with sufficient size. If there is a touch event outside those two tappable areas then they could appear briefly and fade or disappear after a second. If they are tapped correctly we don't need to show them I guess.
